ALTER TABLE MONSTER_SUMMON_LIST_ZONE DROP COLUMN bType
ALTER TABLE MONSTER_RESPAWN_LIST ADD sCount tinyint NOT NULL DEFAULT 1
UPDATE MONSTER_RESPAWN_LIST SET sCount = 1 WHERE sCount = 0 OR sCount IS NULL